name: Flutter CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: '3.22.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: flutter format --dry-run --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-${{ matrix.flutter-version }}
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.flutter-version }}
          path: test-results.xml
          retention-days: 7
